---
title: "Lab 8 Walkthrough"
author: "Desiree Smith"
date: "11/2/2021"
output: html_document
---


```{r}
require(palmerpenguins)

#removing gentoo penguin data
penguin_dat = droplevels(subset(penguins, species != "Gentoo"))

#t-test with the alternative hypothesis that Adelie penguins have shorter flippers than Chinstrap penguin
t.test(flipper_length_mm ~ species, data = penguin_dat, alternative = "less")

install.packages("simpleboot")
require(simpleboot)

dat_adel = droplevels(subset(penguin_dat, species == "Adelie"))


dat_chin = droplevels(subset(penguin_dat, species == "Chinstrap"))


#?
pen_boot = two.boot(dat_adel$flipper_length_mm, dat_chin$flipper_length_mm, FUN = mean, R = 100, na.rm = TRUE)

str(pen_boot$t)

```


```{r veg data}
require("here")
veg_dat = read.csv(here("data", "vegdata.csv"))

boxplot(pine ~ treatment, dat = veg_dat)
```

```{r only clipped and control veg}
dat_tree = droplevels(subset(veg_dat, treatment %in% c("control", "clipped")))

#?
table(dat_tree$treatment)
```

```{r bootstrap}
tree_boot = 
  two.boot(
    subset(dat_tree, treatment == "clipped")$pine,
    subset(dat_tree, treatment == "control")$pine,
    FUN = mean,
    R = 10000,
    na.rm = TRUE
  )

# sum(tree_boot$t >= 0)
# sum(tree_boot$t < 0)

boot.ci(tree_boot)

hist(tree_boot$t, main = "Bootstrap sampling distribution", col= "gold")

#Quantile of tree bootstrap
quantile(tree_boot$t, 0.025)

```

```{r bird data}

require("here")
dat_bird = read.csv(here("data", "bird.sub.csv"))

dat_habitat = read.csv(here("data", "hab.sub.csv"))


dat_all = merge(
  dat_bird, 
  dat_habitat,
  by = c("basin", "sub"))

head(dat_all[, c("b.sidi", "s.sidi")])

# Calculate the sample mean and sd:
b_sidi_mean = mean(dat_all$b.sidi, na.rm = TRUE)
b_sidi_sd   = sd(dat_all$b.sidi, na.rm = TRUE)

# Use the subset-by-name symbol ($) to create a 
# new column of z-standardized values.

dat_all$b.sidi.standardized = (dat_all$b.sidi - b_sidi_mean)/b_sidi_sd

mean(dat_all$b.sidi.standardized)

sd(dat_all$b.sidi.standardized)

plot(
  b.sidi ~ s.sidi, data = dat_all,
  main = "Simpson's diversity indices",
  xlab = "Vegetation cover diversity",
  ylab = "Bird diversity")

```
```{r simple linear regression}

fit_1 = lm(b.sidi ~ s.sidi, data = dat_all)
coef(fit_1)

slope_observed = coef(fit_1)[2]

plot(
  b.sidi ~ s.sidi, data = dat_all,
  main = "Simpson's diversity indices",
  xlab = "Vegetation cover diversity",
  ylab = "Bird diversity")

#?
abline(fit_1)



```

```{r slope coefficient}
dat_1 = 
  subset(
    dat_all,
    select = c(b.sidi, s.sidi))

#Resampling data
index_1 = sample(nrow(dat_1), replace = TRUE)
index_2 = sample(nrow(dat_1), replace = TRUE)

dat_resampled_i = 
  data.frame(
    b.sidi = dat_1$b.sidi[index_1],
    s.sidi = dat_1$s.sidi[index_2]
  )

fit_resampled_i = lm(b.sidi ~ s.sidi, data = dat_resampled_i)
slope_resampled_i = coef(fit_resampled_i)[2]

print(slope_resampled_i)

plot(
  b.sidi ~ s.sidi, data = dat_resampled_i,
  main = "Simpson's diversity indices",
  xlab = "Vegetation cover diversity",
  ylab = "Bird diversity")

#?
abline(fit_resampled_i)

m = 10000 
result = numeric(m) 


for(i in 1:m)
{
  index_1 = sample(nrow(dat_1), replace = TRUE)
index_2 = sample(nrow(dat_1), replace = TRUE)

dat_resampled_i = 
  data.frame(
    b.sidi = dat_1$b.sidi[index_1],
    s.sidi = dat_1$s.sidi[index_2]
  )

fit_resampled_i = lm(b.sidi ~ s.sidi, data = dat_resampled_i)
slope_resampled_i = coef(fit_resampled_i)[2]

print(slope_resampled_i)
  result[i] = coef(fit_resampled_i)[2]
} 


#Null Distribution ?
hist(result, main = "Null Distribution of Regression Slope", xlab = "Slope Parameter")

abline(v = slope_observed, lty = 2, col = "red", lwd = 2)

quantile(result, c(.05))
```

